export enum OrderType {
  BUY = 'BUY',
  SELL = 'SELL',
  MOVING_TRAILING_STOP = 'MOVING_TRAILING_STOP',
  FIXED_TRAILING_STOP = 'FIXED_TRAILING_STOP',
  TAKE_PROFIT = 'TAKE_PROFIT',
  STOP_LOSS = 'STOP_LOSS',
  CONSOLIDATION = 'CONSOLIDATION',
  MOVING_BUY = 'MOVING_BUY'
}
